// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gogahkmraiyykdpmjzjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZ2Foa21yYWl5eWtkcG1qemp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTU0OTIsImV4cCI6MjA2ODA5MTQ5Mn0.RJ34gvUHuJoXhL4HWqsqex_Koin-DLRVUAF2pFnxUrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Geliştirme ortamında RLS politikalarını tamamen devre dışı bırak
  global: {
    headers: {
      'x-supabase-bypass-rls': 'true',
      'x-client-info': 'sleekbloghaven-dev'
    }
  },
  db: {
    schema: 'public'
  }
});